### ISSUE TITLE
Spec error refers to `:args` incorrectly

### ISSUE THREAD

**Issue by bhb** [bhb/expound#79]
```
=> (let [a] 2)
CompilerException clojure.lang.ExceptionInfo: Call to clojure.core/let did not conform to spec:
-- Syntax error -------------------

  ([a] ...)
   ^^^

should have additional elements. The next element ":args" should satisfy

  any?

-- Relevant specs -------

:clojure.core.specs.alpha/bindings:
  (clojure.spec.alpha/and
   clojure.core/vector?
   (clojure.spec.alpha/* :clojure.core.specs.alpha/binding))

-------------------------
```

**Comment by carocad** [comment]
@bhb not sure if this is also relevant but shouldnt the `syntax error` above also show the `let` part?

Currently it seems to be stripped away which puts away part of the context of the expression.

**Comment by bhb** [comment]
@carocad Yes, I agree, it should show the `let` part - that would make things much more clear.

Unfortunately, the data from spec doesn't currently include the function/macro name. It'd be great if this was fixed - please vote for https://dev.clojure.org/jira/browse/CLJ-2271 😄 

Until the above bug is fixed, I'm considering adding a placeholder, so this would look like:

```

  (<f> [a] ...)
   ^^^
```
... to indicate these are args to a macro. What do you think about the idea of using a placeholder? Does it help or just confuse things? Is `<f>` a good enough placeholder? Or would you prefer something more verbose like `<fn-or-macro>`? Something else?

**Comment by carocad** [comment]
@bhb if I would have to choose between no macro info and placeholder I would choose no macro info. Since I am typing the code I can get a pretty rough idea of where the execution failed based on the rest of the info. I think that putting a placeholder would only confuse things since that is nowhere to be found in the code that the user wrote. 

So far I have only encountered this problem for Clojure code since I almost dont use macros. With the inclusion of #44 the error gets so evident that it is very difficult to not identify where the problem is happening.

That might not be true for people that create and use lots of macros though. but I guess if they would have that problem they could report it here 😸

**Comment by bhb** [comment]
@carocad Thanks for the feedback!

**Comment by bhb** [comment]
The fix will be in the next release, currently in 0.7.1-SNAPSHOT.
